name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
        
    - name: Copy files to the test website with the AWS CLI
      run: |
        aws s3 cp s3://contrast-golang-agent/0_2_1/contrast-go ./contrast-go
        chmod u+x ./contrast-go
      
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build -v -o ./bin/mattermost ./cmd/mattermost/
    - name: Build with Contrast
      run: ./contrast-go -v -save build -o ./bin/mattermost-instrumented ./cmd/mattermost/
    
    - name: Archive go binaries
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: |
          bin/mattermost
          bin/mattermost-instrumented

#     - name: Test
#       run: go test -v ./bin/mattermost
