name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-macos:
    name: Build MacOS
    runs-on: macos-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
        
    - name: Copy files to the test website with the AWS CLI
      run: |
        aws s3 cp s3://contrast-golang-agent/0.2.1/darwin/amd64/contrast-go ./contrast-go
        chmod u+x ./contrast-go
      
    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -v -o ./bin/mattermost ./cmd/mattermost/ 2>&1 >&3 | tee build-go-normal.log
      
    - name: Build with Contrast - No Dataflow
      run: ./contrast-go -v -save build -o ./bin/mattermost-contrast-no-dataflow ./cmd/mattermost/ 2>&1 >&3 | tee contrast-build-no-dataflow.log
      
    - name: Build with Contrast - With Dataflow
      run: ./contrast-go -dataflow -v -save build -o ./bin/mattermost-contrast-dataflow ./cmd/mattermost/ 2>&1 >&3 | tee contrast-build-dataflow.log
    
    - name: Archive go binaries
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: |
          bin/mattermost
          bin/mattermost-instrumented

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
        
    - name: Copy files to the test website with the AWS CLI
      run: |
        aws s3 cp s3://contrast-golang-agent/0.2.1/windows/amd64/contrast-go .\contrast-go
        echo $Env:Username
        icacls D:\a\mattermost-server\mattermost-server\contrast-go /grant runneradmin:rx
       
    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -v -o ./bin/mattermost ./cmd/mattermost/
      
    - name: Build with Contrast - No Dataflow
      run: Start-Process -FilePath "./contrast-go" -ArgumentList "-v -save build -o ./bin/mattermost-contrast-no-dataflow ./cmd/mattermost/"
      
    - name: Build with Contrast - With Dataflow
      run: Start-Process -FilePath "./contrast-go" -ArgumentList "-dataflow -v -save build -o ./bin/mattermost-contrast-dataflow ./cmd/mattermost/"
    
    - name: Archive go binaries
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: |
          bin/mattermost
          bin/mattermost-instrumented

  build-ubuntu:
    name: Build Ubuntu
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
        
    - name: Copy files to the test website with the AWS CLI
      run: |
        aws s3 cp s3://contrast-golang-agent/0.2.1/linux/amd64/contrast-go ./contrast-go
        chmod u+x ./contrast-go
      
    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -v -o ./bin/mattermost ./cmd/mattermost/ 2>&1 >&3 | tee build-go-normal.log

    - name: Build with Contrast - No Dataflow
      run: |
        ./contrast-go -v -save build -o ./bin/mattermost-contrast-no-dataflow ./cmd/mattermost/ 2>&1 >&3 | tee contrast-build-no-dataflow.log
        aws s3 cp ./contrast-build-no-dataflow.log s3://contrast-golang-agent/logs/applications/mattermost/contrast-build-no-dataflow.log
      
    - name: Build with Contrast - With Dataflow
      run: |
        ./contrast-go -dataflow -v -save build -o ./bin/mattermost-contrast-dataflow ./cmd/mattermost/ 2>&1 >&3 | tee contrast-build-dataflow.log
        aws s3 cp ./contrast-build-dataflow.log s3://contrast-golang-agent/logs/applications/mattermost/contrast-build-dataflow.log
    
    - name: Archive go binaries
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: |
          bin/mattermost
          bin/mattermost-instrumented

#     - name: Test
#       run: go test -v ./bin/mattermost
